"""Model classes for the forum contents"""

from django.db import models

class Forum(models.Model):
    """Class for forum objects.
        Autogenerated initially"""
    name = models.CharField(max_length=255, null=True, blank=True)

    update_date = models.DateTimeField(auto_now=True)
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

from django.contrib.auth.models import User, Group
class Topic(models.Model):
    """Class for topics of the forums.
    Autogenerated initially"""
    
    created_by = models.ForeignKey(User, null=True, blank=True)

    title = models.CharField(max_length=255, null=True, blank=True)

    forum = models.ForeignKey(Forum, null=True, blank=True)

    update_date = models.DateTimeField(auto_now=True)
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.title
    
class Post(models.Model):
    """Class for posts in a topic.
    Autogenerated initially"""
    
    title = models.CharField(max_length=255, null=True, blank=True)

    body = models.TextField(null=True, blank=True)

    created_by = models.ForeignKey(User, null=True, blank=True)

    topic = models.ForeignKey(Topic, null=True, blank=True)

    update_date = models.DateTimeField(auto_now=True)
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.title
